### ISSUE TITLE
Efficiently verifying that a dataset is normalized

### ISSUE THREAD

**Issue by aaronc** [w3c-ccg/rdf-dataset-canonicalization#11]
I am wondering is there an algorithm or would it be possible to create an algorithm that efficiently verifies that a list of quads is in normalized form?

While the spec document says that most datasets "can be normalized fairly quickly", it does seem like there is a fair amount of complexity. It would seem like there must be a simpler algorithm that can just verify that normalization has been done correctly in say O(n) time just scanning the list of quads and computing hashes along the way. Is that possibly the case?

**Comment by aaronc** [comment]
Okay so no known reasons this would be impossible? It's just that nobody has come up with it yet..?

**Comment by dlongley** [comment]
@aaronc,

Canonicalizing a dataset is a variant of the graph isomorphism problem, one of the most difficult in computer science:

https://en.wikipedia.org/wiki/Graph_isomorphism_problem
