### ISSUE TITLE
Lexicographic Order of Hash is inconsistent

### ISSUE THREAD

**Issue by simon-greatrix** [w3c-ccg/rdf-dataset-canonicalization#14]
Some locales specify a lexicographic ordering where "aa" is after "z". This produces a different hash ordering in the affected locales. You can see an example of this by executing this code snippet in your browser's console:

```js
function letterSort(lang, letters) {
  letters.sort(new Intl.Collator(lang).compare);
  return letters;
}

console.log(letterSort('en', ['fc9b1f', 'aaf4ef']));
// expected output: Array ["aaf4ef", "fc9b1f"]

console.log(letterSort('nn', ['fc9b1f', 'aaf4ef']));
// expected output: Array ["fc9b1f", "aaf4ef"]


console.log(letterSort('da', ['fc9b1f', 'aaf4ef']));
// expected output: Array ["fc9b1f", "aaf4ef"]
```

As you can see when you try it, lexicographic ordering of the hash produces unexpected results for Danish and Norwegian. I would suggest comparing the two hashes as if they were the binary representations of large unsigned integers. This would be consistent with the "lexicographic" ordering for most countries so would not break existing implementations, but would not be dependent upon the applications locale.

**Comment by davidlehn** [comment]
This sounds like a terminology issue.  The intent of "lexicographic sorted" and "lexicographic order" is to do byte-by-byte ordering.  Perhaps the W3C has some other standard name for this.  I thought the default sorting didn't use locales?  Does that per-locale sorting happen with just a plain `letters.sort()` based on some environment value?

**Comment by simon-greatrix** [comment]
I fully understood the intent. It is a terminology issue in my opinion too. 

[Wikipedia](https://en.wikipedia.org/wiki/Lexicographical_order) states lexicographic order is the same as dictionary order or alphabetic order. Dictionaries for Danish and Norwegian apparently put "AA" after "Z". I don't speak either language myself. I've just observed the results of the sorting.

The potential issue is that the standard requires a lexicographic ordering of the hashes and someone might implement it as exactly that. Such an implementation would be technically correct in that it conformed to the standard, but would produce different hashes on the 1-in-256 times a hash has an "aa" in a relevant position. It should not be possible to conform to the standard and get incompatible results.

The one time I know a locale's collation order is always consulted for sorting is when using an SQL `select..order by` style query. If no collation is specified, the database's default collation is used and that could easily be the same as the country where the database is being used. 

I think the standard should use a term that has an indisputable meaning. For example: ASCII order or Unicode code-point order would work.

**Comment by davidlehn** [comment]
- The spec should be updated if we can figure out how best to do so.  I'm not sure "ASCII" or "Unicode code-point" ordering is the proper way to say this.
- Test cases should be added that expose this issue and catch issues in implementations.
- I'm not even sure how to write such tests.  Just using certain strings isn't enough as the only people that might see a failure would be somehow using a certain locale.  It seems a bit odd to recommend implementations check they work in various locales.  Suggestions?
- Just adding the tests is a good first step.  Any suggestions for tests other than what's above?
