### ISSUE TITLE
Redirect old Github pages URL to new one

### ISSUE THREAD

**Issue by TimoGlastra** [w3c-ccg/rdf-dataset-canonicalization#22]
It seems like the repository name was changed recently, resulting in all references to "https://json-ld.github.io/normalization/spec/" being broken. The link to the Github repo automatically redirects, however the Github pages link doesn't.

Maybe something like the approach described here could be used: https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by bumblefudge** [comment]
ahem

**Comment by davidlehn** [comment]
Added a redirect page here: https://github.com/json-ld/json-ld.github.io.

Browsers should now redirect https://json-ld.github.io/normalization/spec/ to https://json-ld.github.io/rdf-dataset-canonicalization/spec/.
