### ISSUE TITLE
Broken link to readable spec

### ISSUE THREAD

**Issue by dbooth-boston** [w3c-ccg/rdf-dataset-canonicalization#29]
At present the link at https://github.com/w3c-ccg/rdf-dataset-canonicalization to https://json-ld.github.io/rdf-dataset-canonicalization/spec/ is 404.  I assume that things are being moved around for the new Working Group, so IDK what the intended correct link would be.

**Comment by gkellogg** [comment]
There’s a PR to fix this: https://github.com/w3c-ccg/rdf-dataset-canonicalization/pull/28.

**Comment by djvs** [comment]
Available via archive.org https://web.archive.org/web/20220831230801/https://json-ld.github.io/rdf-dataset-canonicalization/spec/

**Comment by gkellogg** [comment]
Additionally, I'm going to recreate a pro at GitHub.com/json-ld/rdf-dataset-normalization just with a README and a GH Pages bounce to the new location.

**Comment by gkellogg** [comment]
A new repository was created at https://github.com/json-ld/rdf-dataset-canonicalization with references to the new location.
