### ISSUE TITLE
Observations from a pure functional implementation

### ISSUE THREAD

**Issue by marcelotto** [w3c-ccg/rdf-dataset-canonicalization#31]
I’ve just finished an implementation in Elixir within the [RDF.ex](https://github.com/rdf-elixir/rdf-ex) library and made some observations which might indicate a missing test or some need for clarification, or at least might be of interest for other people trying to implement this in a pure functional way.

I’ve started out with a pure functional implementation without global state (passing down the state instead) and wanted to see how far I get. To my surprise, I got very far with that. The only step in the algorithm which seems to require global state at first glance is step 5.4.5 of the Hash N-Degree Quads algorithm, where in 5.4.5.1 the recursive call of the algorithm is done to produce the issuer copy of the next iteration (5.4.5.4), but in 5.4.5.2 issuing an identifier still on the old issuer copy. 

But it’s actually quite easy to circumvent this need for global state here with an additional step in which I check if the result issuer from 5.4.5.1 is equal to the current issuer copy and, if that’s the case, also apply the issuing of an identifier for *related* with the result issuer. This should lead to equivalent results as the original algorithm. It seems, however, that it never can happen that the result issuer is the same as the issuer copy passed into the Hash N-Degree Quads algorithm in 5.4.5.1. Theoretically, this could only happen if the *hash to related blank nodes map* produced in the first three steps would be empty, so that the loop in step 5 would never be entered and overwriting the issuer reference with a chosen issuer copy. However, I’m not sure if this can actually happen in practice. At least none of the test cases in the test suite leads to a situation where result issuer is equal to the issuer copy in 5.4.5.1. That’s why my pure functional implementation even passes all tests without this additional step.

Nevertheless, I’ve added this additional step just because of this theoretical possibility. It would be good to know if this step is actually required, since only for the issuer equality check of this additional step, I had to introduce reference-tracking for the identifier issuers, which is relatively costly performance-wise. If it is indeed possible, this should be covered with a test case to validate the correct state handling of an implementation in this case.

**Comment by gkellogg** [comment]
That's great, but note that the work has moved on to the RDF Dataset Canonicalization WG, which recently published a [First Public Working Draft](https://www.w3.org/TR/rdf-canon/), which has minor changes from the CG draft. We're continue to to work on the document at https://github.com/w3c/rdf-canon/, which should be used for future issues.

Regarding the global state, there should be no global state involved. The [canonicalization state](https://www.w3.org/TR/rdf-canon/#dfn-canonicalization-state) includes the [canonical issuer](https://www.w3.org/TR/rdf-canon/#dfn-canonical-issuer), which is passed between algorithm invocations. Step [5.4.5.1](https://www.w3.org/TR/rdf-canon/#hndq-5-4-5-1) invokes the Hash N-Degree Quads algorithm recursively, and it should be more explicit that this includes the canonicalization state, which is listed as one of the algorithm inputs, which I'll add as an issue to fix in an upcoming draft.

It would be great if you could try making this change and report back if that satisfies your issue on the rdf-canon repo.

**Comment by marcelotto** [comment]
@gkellogg Since your created issue on the rdf-canon repo didn't address my problem, I've created another one on this repo to continue the discussion there: https://github.com/w3c/rdf-canon/issues/48
